name: ci
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v11
      - run: sbt "; scalafmtCheckAll; scalafmtSbtCheck" "; scalafixEnable; scalafixAll --check"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - 8
          - 11
        scala:
          - 2.11.12
          - 2.12.14
          - 2.13.6
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v11
      - run: |
          sbt ++2.12.12 coverage test coverageReport
          bash <(curl -s https://codecov.io/bash)
  mimaReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} mimaReportBinaryIssues"
    strategy:
      matrix:
        java:
          - 8
          - 11
        scala:
          - 2.11.12
          - 2.12.14
          - 2.13.6
  microsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Ruby setup
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.6
      - run: |
          gem install sass
          gem install jekyll -v 3.2.1
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v11
      - run: sbt docs/makeMicrosite
