name: ci
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: 17
      - run: sbt "; scalafmtCheckAll; scalafmtSbtCheck" "; scalafixEnable; scalafixAll --check"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 17
        scala:
          - 2.11.12
          - 2.12.17
          - 2.13.10
          - 3.3.0
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: 17
      - run: |
          sbt ++2.12.17 coverage test coverageReport
          bash <(curl -s https://codecov.io/bash)
  mimaReport:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} mimaReportBinaryIssues"
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 17
        scala:
          - 2.11.12
          - 2.12.17
          - 2.13.10
  microsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: |
          gem install sass
          gem install jekyll -v 3.2.1
      - uses: actions/setup-java@v3
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: 17
